<?php
/**
 * Creative Agency theme setup.
 *
 * Creative Agency is a block theme: the layout lives in templates/*.html, the
 * design system in theme.json (generated by .dev/build_theme.py), and the
 * sections in patterns/*.php. This file carries only what those cannot
 * express — supports flags, asset enqueues, block styles, pattern categories,
 * and the guards that keep the theme graceful when a plugin it can use is not
 * installed.
 *
 * @package Creative_Agency
 */

defined( 'ABSPATH' ) || exit;

define( 'CREATIVE_AGENCY_VERSION', '1.0.0' );

/**
 * Theme supports.
 */
function creative_agency_setup() {
	load_theme_textdomain( 'creative-agency', get_template_directory() . '/languages' );

	add_theme_support( 'title-tag' );
	add_theme_support( 'post-thumbnails' );
	add_theme_support( 'automatic-feed-links' );
	add_theme_support( 'html5', array( 'search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script' ) );
	add_theme_support( 'editor-styles' );
	add_theme_support( 'responsive-embeds' );
	add_theme_support( 'align-wide' );
	add_theme_support( 'wp-block-styles' );
	add_theme_support(
		'custom-logo',
		array(
			'height'      => 100,
			'width'       => 100,
			'flex-height' => true,
			'flex-width'  => true,
		)
	);

	// style.css is loaded into the editor canvas too, so the components below
	// look the same there as on the front end.
	add_editor_style( 'style.css' );
}
add_action( 'after_setup_theme', 'creative_agency_setup' );

/**
 * Front-end styles.
 */
function creative_agency_enqueue_styles() {
	wp_enqueue_style( 'creative-agency-style', get_stylesheet_uri(), array(), CREATIVE_AGENCY_VERSION );
}
add_action( 'wp_enqueue_scripts', 'creative_agency_enqueue_styles' );

/**
 * Block style variations.
 *
 * Registered here rather than in theme.json because a style variation needs a
 * label for the editor's Styles panel. Each is a class style.css already
 * carries — never behind a `style_handle`, which only loads while WordPress
 * serves separate block assets and which any plugin can switch off — so a
 * pattern can ask for it by name and an editor can apply it to their own
 * blocks too.
 */
function creative_agency_register_block_styles() {
	$styles = array(
		'core/button'    => array(
			array( 'creative-agency-underline', __( 'Underlined link', 'creative-agency' ) ),
		),
		'core/group'     => array(
			array( 'creative-agency-card', __( 'Outlined card', 'creative-agency' ) ),
			array( 'creative-agency-panel', __( 'Panel', 'creative-agency' ) ),
		),
		'core/paragraph' => array(
			array( 'creative-agency-watermark', __( 'Watermark', 'creative-agency' ) ),
		),
		'core/heading'   => array(
			array( 'creative-agency-marked', __( 'Marked', 'creative-agency' ) ),
		),
		'core/list'      => array(
			array( 'creative-agency-dots', __( 'Yellow dots', 'creative-agency' ) ),
			array( 'creative-agency-links', __( 'Plain links', 'creative-agency' ) ),
		),
	);

	foreach ( $styles as $block => $variations ) {
		foreach ( $variations as $variation ) {
			list( $name, $label ) = $variation;
			register_block_style(
				$block,
				array(
					'name'  => $name,
					'label' => $label,
				)
			);
		}
	}
}
add_action( 'init', 'creative_agency_register_block_styles' );

/**
 * Hide the giant pale section words from screen readers.
 *
 * "Projects", "Services" and "Quick fact" sit behind the real section titles
 * as decoration. Read aloud they would be a second, meaningless heading before
 * every section.
 *
 * @param string $content Rendered block.
 * @param array  $block   Block data.
 * @return string
 */
function creative_agency_watermark_markup( $content, $block ) {
	$classes = isset( $block['attrs']['className'] ) ? $block['attrs']['className'] : '';
	if ( false === strpos( $classes, 'is-style-creative-agency-watermark' ) ) {
		return $content;
	}
	return preg_replace( '/^(\s*<p\b)/', '$1 aria-hidden="true"', $content, 1 );
}
add_filter( 'render_block_core/paragraph', 'creative_agency_watermark_markup', 10, 2 );

/**
 * Expand shortcodes in a Shortcode block wherever it renders.
 *
 * core/shortcode's own render only runs wpautop(); the expansion normally comes
 * from `the_content`, which does not run for a block template. Without this,
 * the contact section placed in a template would print its shortcode as text.
 * Running do_shortcode() on already expanded output changes nothing.
 *
 * @param string $content Rendered block.
 * @return string
 */
function creative_agency_render_shortcode_block( $content ) {
	return do_shortcode( $content );
}
add_filter( 'render_block_core/shortcode', 'creative_agency_render_shortcode_block' );

/**
 * The sticky header, the counting figures and the video popup.
 *
 * Deferred and in the footer: everything the script does is an enhancement,
 * so it never needs to hold up rendering. `creative_agency_enable_scroll_animations`
 * switches off the counting and leaves the header and the video popup, which
 * are behaviour rather than decoration.
 *
 * The settings go in as JSON, not through wp_localize_script(), which turns
 * `false` into an empty string that the script would read as "on".
 */
function creative_agency_enqueue_interactions() {
	wp_enqueue_script(
		'creative-agency-interactions',
		get_template_directory_uri() . '/assets/js/interactions.js',
		array(),
		CREATIVE_AGENCY_VERSION,
		array(
			'in_footer' => true,
			'strategy'  => 'defer',
		)
	);

	wp_add_inline_script(
		'creative-agency-interactions',
		'window.creativeAgencyMotion = ' . wp_json_encode(
			array(
				'enabled'    => (bool) apply_filters( 'creative_agency_enable_scroll_animations', true ),
				'sticky'     => (bool) apply_filters( 'creative_agency_sticky_header', true ),
				'videoLabel' => __( 'Video', 'creative-agency' ),
				'closeLabel' => __( 'Close video', 'creative-agency' ),
			)
		) . ';',
		'before'
	);
}
add_action( 'wp_enqueue_scripts', 'creative_agency_enqueue_interactions' );

/**
 * Pattern categories.
 *
 * Registered on `init` so the labels are translated, and before patterns/*.php
 * are read, which is what WordPress does with a theme's patterns directory.
 */
function creative_agency_register_pattern_categories() {
	$categories = array(
		'creative-agency-sections' => array(
			'label'       => __( 'Creative Agency: sections', 'creative-agency' ),
			'description' => __( 'Full-width sections for building pages.', 'creative-agency' ),
		),
		'creative-agency-pages'    => array(
			'label'       => __( 'Creative Agency: pages', 'creative-agency' ),
			'description' => __( 'Complete page layouts.', 'creative-agency' ),
		),
	);

	foreach ( $categories as $slug => $args ) {
		register_block_pattern_category( $slug, $args );
	}
}
add_action( 'init', 'creative_agency_register_pattern_categories' );

require get_template_directory() . '/inc/front-page-setup.php';
require get_template_directory() . '/inc/contact-form.php';
require get_template_directory() . '/inc/forms.php';
require get_template_directory() . '/inc/woocommerce.php';
require get_template_directory() . '/inc/scheme.php';
require get_template_directory() . '/inc/updates.php';
